title: Journey Through Coding
author: NParsons76
email: nparsons76@outlook.com
date: 2020-11-29
description: A journey with me through the very intimidating world of coding that I am starting. I have played around with coding for some time but recently have been diving in on it, finally!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
